---
title: "aic"
author: "jt-miller"
date: "2023-12-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### MODEL SELECTION: AIC 

The null model is the true model: the mean in known and the variance sigsq is against 
Alternative is the data is Normal, unk mean, knwon variance 
```{r}
muo <- 100 # null mean
sig <- 15 # null variance
nvec <- 2:50 # 49 sample size
len <- length(nvec)
B <- 10000 # for every sample size create 10,000 datasets
pct.err <- rep(0,len)

k <- 2 # Arbitrary!

for(i in 1:len){
  
  AICmat <- matrix(0, nrows=B, ncol=2)
  is.best.wrong <- rep(0,B)
  
  for(j in 1:B){
    
    # Simulate under the null
    sim.samp <- rnorm(n=nvec[i], mean = muo, sd = sig) # sim under the null
    log.Lo <- sum(dnorm(sim.samp, mean = muo, sd=sig, log = TRUE))
    AICo <- -2*log.Lo + 2*0 # zero parameters
     AICmat[j,1] <- AICo
    # simulate under the alternative 
    xbar <- mean(sim.samp) # est one parameter
    
    log.L1 <- sum(dnorm(x=sim.samp, mean = xbar, sd=sig, log = TRUE))
    AIC1 <- -2*log.L1 + 2*1 # one params
    AICmat[j,2] <- AIC1
    
    is.best.wrong[j] <- (AICo - AIC1 >= k) # If so, I am saying that model 1 is best, which we know is wrong 
    

    
  }
  
  pct.err[i] <- sum(is.best.wrong)/B
  
}

plot(nvec, pct.err, type = "l", col = "red", lwd=2, ylim=c(0, 0.20))



mvec <- 1-pchisq(q=k+log(nvec), df = 1) # for k=2

points(nvec,mvec, type="l", col="blue", lwd=2)

```

